

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



jobs:
  postgres:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Node start
      run: npm start -C gate-simulator & sleep 10
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run application
      run: java -jar artifacts/aqa-shop.jar & sleep 30
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test -Dselenide.headless=true --info

  mysql:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: yes
          MYSQL_DATABASE: mysql
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
        ports:
          - 3306:3306


    steps:
    - uses: actions/checkout@v2
    - name: Node start
      run: npm start -C gate-simulator & sleep 10
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run application
      run: java -jar -Dspring.profiles.active=mysql artifacts/aqa-shop.jar & sleep 30
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test -Dselenide.headless=true -Durl="jdbc:mysql://localhost:3306/mysql" --info
